--check constrains
ALTER TABLE DOCENTE ADD CONSTRAINT CHK_DOCENTE_DESDE CHECK (DOCENTE_DESDE <= CURRENT_DATE);
ALTER TABLE ENTREGA ADD CONSTRAINT CHK_CALIFICACION_RANGE CHECK (CALIFICACION BETWEEN 0 AND 100 OR CALIFICACION IS NULL);
ALTER TABLE ESTUDIANTE ADD CONSTRAINT CHK_CORREO_ESTUDIANTIL_VALIDO CHECK (CORREO_ESTIDIANTIL LIKE '%@%');
ALTER TABLE USUARIO ADD CONSTRAINT CHK_FECHA_NAC_VALIDA CHECK (FECHA_NAC <= CURRENT_DATE - INTERVAL '10 years');
ALTER TABLE ROL ADD CONSTRAINT CHK_NOM_ROL_NOT_EMPTY CHECK (TRIM(NOM_ROL) <> '');
ALTER TABLE TAREA ADD CONSTRAINT CHK_FECHA_ASIGNACION_ENTREGA CHECK (FECHA_ASIGNACION <= FECHA_ENTREGA OR FECHA_ENTREGA IS NULL);
ALTER TABLE FUNCION ADD CONSTRAINT CHK_NOM_FUNCION_NOT_EMPTY CHECK (TRIM(NOM_FUNCION) <> '');
ALTER TABLE GRADO_ACADEMICO ADD CONSTRAINT CHK_GRADO_ACAD_NOT_EMPTY CHECK (TRIM(GRADO_ACAD) <> '');
ALTER TABLE LICENCIATURA ADD CONSTRAINT CHK_NOM_LICENCIATURA_NOT_EMPTY CHECK (TRIM(NOM_LICENCIATURA) <> '');
ALTER TABLE MATERIA ADD CONSTRAINT CHK_NOMBRE_MATERIA_NOT_EMPTY CHECK (TRIM(NOMBRE_MATERIA) <> '');
ALTER TABLE MATERIA ADD CONSTRAINT CHK_DESCRIPCION2_NOT_EMPTY CHECK (TRIM(DESCRIPCION2) <> '');
ALTER TABLE TAREA ADD CONSTRAINT CHK_NOMBRE_TAREA_NOT_EMPTY CHECK (TRIM(NOMBRE_TAREA) <> '');
ALTER TABLE TIPO_ARCHIVO ADD CONSTRAINT CHK_TIPO_ARCHIVO_NOT_EMPTY CHECK (TRIM(TIPO_ARCHIVO) <> '');
ALTER TABLE UI ADD CONSTRAINT CHK_NOMBRE_UI_NOT_EMPTY CHECK (TRIM(NOMBRE_UI) <> '');
ALTER TABLE USUARIO ADD CONSTRAINT CHK_NOMBRE_NOT_EMPTY CHECK (TRIM(NOMBRE) <> '');
ALTER TABLE USUARIO ADD CONSTRAINT CHK_CONTRASENIA_NOT_EMPTY CHECK (TRIM(CONTRASENIA) <> '');
ALTER TABLE COMENTARIO ADD CONSTRAINT CHK_COMENTARIO_LENGTH CHECK (LENGTH(COMENTARIO) <= 150 OR COMENTARIO IS NULL);
ALTER TABLE MATERIA ADD CONSTRAINT CHK_DESCRIPCION2_LENGTH CHECK (LENGTH(DESCRIPCION2) <= 150);
ALTER TABLE TAREA ADD CONSTRAINT CHK_DESCRIPCION_TAREA_LENGTH CHECK (LENGTH(DESCRIPCION_TAREA) <= 150 OR DESCRIPCION_TAREA IS NULL);
ALTER TABLE USUARIO ADD CONSTRAINT CHK_CORREO_ACADEMICO_VALIDO CHECK (correo_academico LIKE '%@%');

