SELECT * FROM COMENTARIO;
SELECT * FROM COMENTARIO_ENTREGA;
SELECT * FROM DOCENTE;--
SELECT * FROM ENTREGA;
SELECT * FROM ESTUDIANTE;--
SELECT * FROM ESTUDIANTE_ENTREGA;
SELECT * FROM FUNCION;
SELECT * FROM FUNCION_UI;
SELECT * FROM GRADO_ACADEMICO;--
SELECT * FROM INSCRIPCION;
SELECT * FROM LICENCIATURA;
SELECT * FROM MATERIA;--
SELECT * FROM MATERIA_TAREA;
SELECT * FROM ROL;--
SELECT * FROM ROL_FUNCION;--
SELECT * FROM ROL_usuario;--
SELECT * FROM SESION;
SELECT * FROM TAREA;
SELECT * FROM TAREA_ENTREGA;
SELECT * FROM TIPO_ARCHIVO;--
SELECT * FROM UI;
SELECT * FROM USUARIO;--
SELECT * FROM LOG_BD

select nombre_materia from materia where id_docente=5



SELECT distinct
    t.ID_TAREA, 
    t.NOMBRE_TAREA, 
    t.FECHA_ASIGNACION, 
    t.FECHA_ENTREGA, 
    t.DESCRIPCION_TAREA,
    e.ARCHIVO
FROM TAREA t
JOIN MATERIA_TAREA mt ON t.ID_TAREA = mt.ID_TAREA
JOIN INSCRIPCION i ON mt.ID_MATERIA = i.ID_MATERIA
JOIN ESTUDIANTE_ENTREGA ee ON i.ID_ESTUDIANTE = ee.ID_ESTUDIANTE
JOIN ENTREGA e ON ee.ID_ENTREGA = e.ID_ENTREGA
WHERE mt.ID_DOCENTE = 5 AND e.ARCHIVO IS NOT NULL;