SELECT * FROM COMENTARIO;
SELECT * FROM COMENTARIO_ENTREGA;
SELECT * FROM DOCENTE;--
SELECT * FROM ENTREGA;
SELECT * FROM ESTUDIANTE;--
SELECT * FROM ESTUDIANTE_ENTREGA;
SELECT * FROM FUNCION;
SELECT * FROM FUNCION_UI;
SELECT * FROM GRADO_ACADEMICO;--
SELECT * FROM INSCRIPCION;
SELECT * FROM LICENCIATURA;
SELECT * FROM MATERIA;--
SELECT * FROM MATERIA_TAREA;
SELECT * FROM ROL;--
SELECT * FROM ROL_FUNCION;--
SELECT * FROM ROL_USERN;--
SELECT * FROM SESION;
SELECT * FROM TAREA;
SELECT * FROM TAREA_ENTREGA;
SELECT * FROM TIPO_ARCHIVO;--
SELECT * FROM UI;
SELECT * FROM USUARIO;--
SELECT * FROM LOG_BD

select nombre_materia from materia where id_docente=5



